// Builds the PartyBox port's compact solved tables from the shipped primary binaries.
// Usage: node partybox/build-tables.mjs [outDir]   (default: partybox/server/optimal)
// Keeps one Float64 per canonical state: an upper subtotal that can no longer reach 63 has the
// same value as subtotal 0 (generator.cpp canonicalIndex). Every copy is checked bit for bit
// before it is dropped, so the compact table is lossless against tables/<mode>.bin.
import assert from 'node:assert/strict';
import crypto from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';

const job=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const out=path.resolve(process.argv[2]??path.join(job,'partybox/server/optimal'));
const ENTRIES=359616;
const reach=Array.from({length:64},(_,mask)=>{
  let sums=new Set([0]);
  for(let face=1;face<=6;face++)if(mask&(1<<(face-1))){const next=new Set();for(const u of sums)for(let n=0;n<=5;n++)next.add(Math.min(63,u+face*n));sums=next;}
  return [...sums].sort((a,b)=>a-b);
});
const left=Array.from({length:64},(_,mask)=>{let sum=0;for(let face=1;face<=6;face++)if(!(mask&(1<<(face-1))))sum+=5*face;return sum;});
const sha=bytes=>crypto.createHash('sha256').update(bytes).digest('hex');
fs.mkdirSync(out,{recursive:true});
const facts=[];
for(const mode of ['official','published']){
  const source=fs.readFileSync(path.join(job,`tables/${mode}.bin`));assert.equal(source.length,8388608);
  const at=(mask,upper,bonus)=>(mask+upper*8192+(bonus?524288:0))*8;
  const parts=[];let valid=0,copies=0;
  for(let mask=0;mask<8192;mask++)for(const bonus of mask&2048?[false,true]:[false]){
    const low=mask&63;
    for(const upper of reach[low]){
      valid++;const canonical=upper+left[low]<63?0:upper;
      const value=source.subarray(at(mask,upper,bonus),at(mask,upper,bonus)+8);
      assert.ok(Number.isFinite(value.readDoubleLE(0)),`${mode}: valid state without a value`);
      if(canonical===upper)parts.push(value);
      else{assert.ok(value.equals(source.subarray(at(mask,canonical,bonus),at(mask,canonical,bonus)+8)),`${mode}: copy differs`);copies++;}
    }
  }
  const raw=Buffer.concat(parts);
  assert.equal(valid,536448);assert.equal(parts.length,ENTRIES);assert.equal(copies,valid-ENTRIES);assert.equal(raw.length,ENTRIES*8);
  const name=mode.toUpperCase(),file=path.join(out,`tables-${mode}.generated.ts`);
  fs.writeFileSync(file,[
    `// Generated by B07 partybox/build-tables.mjs from tables/${mode}.bin (sha256 ${sha(source)}). Do not edit.`,
    `// ${ENTRIES} canonical solved values (${mode} Joker rule), Float64 little-endian, base64. Layout: tables.ts.`,
    `export const SOLVED_${name}_SHA256 = '${sha(raw)}';`,
    `export const SOLVED_${name} =`,
    `  '${raw.toString('base64')}';`,
    '',
  ].join('\n'));
  facts.push({mode,validStates:valid,canonicalEntries:parts.length,bitIdenticalCopies:copies,rawBytes:raw.length,rawSHA256:sha(raw),moduleBytes:fs.statSync(file).size,file:path.relative(job,file)});
}
console.log(JSON.stringify(facts));
