import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {readFileSync,writeFileSync} from 'node:fs';
import * as p from '../dist/ttr.js';import * as r from '../dist/reference.js';
import {cards,freeze,compare} from './common.mjs';
const data=JSON.parse(readFileSync('usa.json','utf8'));const routes=freeze(data.routes),tickets=freeze(data.baseTickets);const pair=x=>[x.a,x.b].sort().join('|');const byId=new Map(routes.map(x=>[x.id,x]));const pairById=new Map(routes.map(x=>[x.id,pair(x)]));
const results=[];
for(const seed of [1,2,3]){const random=r.seeded(seed),pick=n=>Math.floor(random()*n),shuffle=a=>{for(let i=a.length-1;i>0;i--){const j=pick(i+1);[a[i],a[j]]=[a[j],a[i]];}return a;};const digest=createHash('sha256');let turns=0,claims=0,blindDraws=0,ticketDraws=0,recycles=0,maxOwned=0,minTurns=Infinity,maxTurns=0,checks=0;const samples=[];
for(let sample=0;sample<2000;sample++){const n=2+pick(4);let deck=shuffle(cards.flatMap(c=>Array(c==='locomotive'?14:12).fill(c))),discard=[],market=[];let state={playerCount:n,players:Array.from({length:n},(_,i)=>({id:`p${i}`,cards:Object.fromEntries(cards.map(c=>[c,0])),trainsRemaining:45,ticketIds:[]})),claims:{}};const draw=()=>{if(deck.length===0&&discard.length){deck=shuffle(discard);discard=[];recycles++;}return deck.pop();};for(let k=0;k<4;k++)for(const player of state.players)player.cards[draw()]++;for(let reset=0;reset<100;reset++){market=Array.from({length:5},draw);if(market.filter(c=>c==='locomotive').length<3)break;discard.push(...market);market=[];}assert.equal(market.length,5);assert.ok(market.filter(c=>c==='locomotive').length<3);
let ticketDeck=shuffle(tickets.map(t=>t.id));for(const player of state.players){const offered=ticketDeck.splice(0,3),keep=2+pick(2);player.ticketIds=offered.slice(0,keep);ticketDeck.push(...offered.slice(keep));}
let final=-1,trigger=-1,turn=0,playerIndex=pick(n),finalTurns=0;
while(final!==0){assert.ok(turn<1500,`game must reach real final round seed${seed}/game${sample}, remaining=${state.players.map(x=>x.trainsRemaining)}`);const wasFinal=final>=0;let player=state.players[playerIndex];const ownersByPair=new Map();for(const [id,owner]of Object.entries(state.claims)){const key=pairById.get(id);ownersByPair.set(key,[...(ownersByPair.get(key)??[]),owner]);}const candidates=[];for(const route of routes){if(Object.hasOwn(state.claims,route.id)||route.length>player.trainsRemaining)continue;const owners=ownersByPair.get(pairById.get(route.id))??[];const conflicts=owners.length&&(n<=3||owners.includes(player.id));if(conflicts)continue;if(player.trainsRemaining<=8&&player.trainsRemaining-route.length>2)continue;const colors=route.color==='gray'?cards.slice(0,8):[route.color];for(const color of colors){const colored=Math.min(player.cards[color],route.length),locos=route.length-colored;if(locos<=player.cards.locomotive){candidates.push({routeId:route.id,playerId:player.id,cards:[...Array(colored).fill(color),...Array(locos).fill('locomotive')]});break;}}}
if(candidates.length&&(random()<.8||player.trainsRemaining<=8)){const request=candidates[pick(candidates.length)];assert.equal(compare(p,r,'canClaim',[routes,state,request],`legal game${seed}/${sample}/${turn}`).value,true);const applied=compare(p,r,'applyClaim',[routes,state,request],`apply game${seed}/${sample}/${turn}`);state=structuredClone(applied.value);discard.push(...request.cards);claims++;checks+=2;player=state.players[playerIndex];if(final<0&&player.trainsRemaining<=2){final=n;trigger=playerIndex;}}
else if(ticketDeck.length&&random()<.035){state=structuredClone(state);player=state.players[playerIndex];const offered=ticketDeck.splice(0,3),keep=1+pick(offered.length);player.ticketIds.push(...offered.slice(0,keep));ticketDeck.push(...offered.slice(keep));ticketDraws++;}
else{state=structuredClone(state);player=state.players[playerIndex];for(let k=0;k<2;k++){const c=draw();if(c!==undefined){player.cards[c]++;blindDraws++;}}}
// Every legal turn preserves physical pieces. The final round includes its triggering player.
const physical=Object.fromEntries(cards.map(c=>[c,0]));for(const x of state.players)for(const c of cards)physical[c]+=x.cards[c];for(const c of [...deck,...discard,...market])physical[c]++;for(const c of cards){assert.equal(physical[c],c==='locomotive'?14:12);checks++;}for(const x of state.players){const ids=Object.entries(state.claims).filter(([,owner])=>owner===x.id).map(([id])=>id);assert.equal(x.trainsRemaining+ids.reduce((sum,id)=>sum+byId.get(id).length,0),45);maxOwned=Math.max(maxOwned,ids.length);checks++;}const held=[...ticketDeck,...state.players.flatMap(x=>x.ticketIds)];assert.equal(held.length,30);assert.equal(new Set(held).size,30);checks+=2;
if(wasFinal){final--;finalTurns++;}turn++;playerIndex=(playerIndex+1)%n;}
assert.equal(finalTurns,n);assert.ok(trigger>=0);assert.ok(state.players[trigger].trainsRemaining<=2);const scores=compare(p,r,'scoreGame',[routes,tickets,state],`full game score${seed}/${sample}`).value;checks++;digest.update(JSON.stringify({state,scores,turn,trigger})+'\n');if(sample===0||sample===1999)samples.push({sample,turn,trigger,state,scores});turns+=turn;minTurns=Math.min(minTurns,turn);maxTurns=Math.max(maxTurns,turn);if(sample%100===99)console.log(JSON.stringify({suite:'games',seed,completed:sample+1,turns}));}
const result={seed,completedGames:2000,endedByTrainsAndFullFinalRound:2000,turns,claims,blindDraws,ticketDraws,recycles,maxOwned,minTurns,maxTurns,checks,replaySHA256:digest.digest('hex'),samples,passed:true};results.push(result);writeFileSync('test-output/games.json',JSON.stringify({passed:true,seeds:results},null,2)+'\n');}
