import assert from 'node:assert/strict';
import {cards,game,edge,compare} from './common.mjs';
export function goldens(p,r,seed){let checks=0;assert.equal(Object.isFrozen(p.CARDS)&&Object.isFrozen(p.ROUTE_POINTS),true);assert.throws(()=>p.CARDS.push('cyan'),TypeError);assert.throws(()=>{p.ROUTE_POINTS[6]=16;},TypeError);assert.equal(p.CARDS.length,9);checks+=4;const check=(name,args,label)=>{checks++;return compare(p,r,name,args,`seed${seed}: ${label}`);};
const routes=[edge('r','A','B',2,'red'),edge('parallel','B','A',2,'red'),edge('g','B','C',3),edge('one','C','D',1,'blue'),edge('six','D','E',6)];
for(const n of [2,3,4,5]){const request={routeId:'r',playerId:'p0',cards:['red','locomotive']};check('canClaim',[routes,game(n),request],`legal ${n}`);check('applyClaim',[routes,game(n),request],`immutable apply ${n}`);for(const owner of ['p0','p1']){const s=game(n);s.claims.r='p0';check('canClaim',[routes,s,{...request,routeId:'parallel',playerId:owner}],`parallel ${n}/${owner}`);}const illegal=game(n);illegal.claims.r='p0';illegal.claims.parallel='p1';check('canClaim',[routes,illegal,{routeId:'g',playerId:'p0',cards:['red','red','red']}],`existing parallels ${n}`);}
for(const id of ['one','six']){const route=routes.find(x=>x.id===id);const s=game(2);s.players[0].trainsRemaining=route.length;s.players[0].cards[route.color==='gray'?'green':route.color]=route.length;check('canClaim',[routes,s,{routeId:id,playerId:'p0',cards:Array(route.length).fill(route.color==='gray'?'green':route.color)}],'exact trains and cards');}
for(const spend of [[],['red'],['red','blue'],['red','red'],['locomotive','locomotive'],new Array(2),['red',undefined],['invalid','red']])check('canClaim',[routes,game(2),{routeId:'r',playerId:'p0',cards:spend}],'colored payment');
for(const spend of [['red','blue','locomotive'],['green','green','locomotive'],['locomotive','locomotive','locomotive']])check('canClaim',[routes,game(2),{routeId:'g',playerId:'p0',cards:spend}],'gray payment');
for(const modify of [s=>s.playerCount=1,s=>s.players.pop(),s=>s.players[0].cards.red=-1,s=>s.players[0].cards.red=NaN,s=>s.players[0].cards.red=Number.MAX_SAFE_INTEGER+1,s=>s.players[0].ticketIds=new Array(1),s=>s.players[0].cards.extra=1,s=>delete s.players[0].cards.red,s=>s.claims.unknown='p0',s=>s.claims.r='unknown']){const s=game(2);modify(s);check('canClaim',[routes,s,{routeId:'r',playerId:'p0',cards:['red','red']}],'invalid state');}
for(const ids of [[],['r'],['r','r'],['unknown'],new Array(1),['r',undefined]]){check('longestTrail',[routes,ids],'owned validation');check('ticketComplete',[routes,ids,{id:'t',a:'A',b:'B',points:1}],'ticket owned validation');}
for(const [a,b]of [['A','A'],['B','A'],['D','A'],['A','D'],['missing','A']])check('ticketComplete',[routes,['r','g','one'],{id:'t',a,b,points:1}],'connectivity directions');
const star=Array.from({length:4},(_,i)=>edge(`s${i}`,'hub',`leaf${i}`,i+1));assert.equal(check('longestTrail',[star,star.map(x=>x.id)],'four odd vertices').value,7);
const separated=[edge('a','A','B',2),edge('b','C','D',6)];assert.equal(check('longestTrail',[separated,['a','b']],'disconnected weighted').value,6);
const trail=[edge('a','A','B',2),edge('b','B','C',3),edge('c','C','A',4),edge('d','A','D',5),edge('loop','D','D',6)];assert.equal(check('longestTrail',[trail,trail.map(x=>x.id)],'reuse city and loop').value,20);
for(const count of [44,80]){const chain=Array.from({length:count},(_,i)=>edge(`e${i}`,`v${i}`,`v${i+1}`,1));assert.equal(check('longestTrail',[chain,chain.map(x=>x.id)],'no edge cap').value,count);}
const scoreRoutes=[edge('s1','A','B',6),edge('s2','C','D',6)];const tickets=[{id:'complete',a:'A',b:'B',points:10},{id:'fail',a:'A',b:'C',points:4}];const s=game(2);s.claims={s1:'p0',s2:'p1'};s.players[0].ticketIds=['fail','complete'];const score=check('scoreGame',[scoreRoutes,tickets,s],'positive tie and signed tickets').value;assert.equal(score[0].routePoints,15);assert.equal(score[0].ticketPoints,6);assert.deepEqual(score.map(x=>x.longestBonus),[10,10]);assert.deepEqual(score[0].completedTicketIds,['complete']);check('scoreGame',[scoreRoutes,[],game(2)],'empty no bonus');
for(const invalid of [NaN,Infinity,1.5,Number.MAX_SAFE_INTEGER+1]){assert.throws(()=>p.seeded(invalid),RangeError);assert.throws(()=>r.seeded(invalid),RangeError);checks++;}
const random=r.seeded(seed);for(let i=0;i<100;i++){const v=2+Math.floor(random()*6),n=Math.floor(random()*11),es=Array.from({length:n},(_,j)=>edge(`e${j}`,`v${Math.floor(random()*v)}`,`v${Math.floor(random()*v)}`,1+Math.floor(random()*6)));check('longestTrail',[es,es.map(x=>x.id)],`mutation random ${i}`);}
return{seed,checks,passed:true};}
