export const mutations=[
 ['easy exploration disabled','easy:1,normal:.5','easy:0,normal:.5'],
 ['normal exploration disabled','normal:.5,hard:.1','normal:0,hard:.1'],
 ['hard exploration disabled','hard:.1,master:0','hard:0,master:0'],
 ['master explores all','hard:.1,master:0','hard:.1,master:1'],
 ['easy always purchases','easy:.5,normal:.85','easy:1,normal:.85'],
 ['normal always purchases','normal:.85,hard:.98','normal:1,hard:.98'],
 ['hard always purchases','hard:.98,master:1','hard:1,master:1'],
 ['master half purchases','hard:.98,master:1','hard:.98,master:.5'],
 ['negative RNG accepted','value>=0','value>=-1'],
 ['RNG endpoint one accepted','value<1','value<=1'],
 ['throwing RNG replaced by zero','catch {return null;}','catch {return 0;}'],
 ['branch allowed at zero turns','if(state.turnsLeft===0)return null;','if(state.turnsLeft<0)return null;'],
 ['actions allowed at zero turns','if(state.turnsLeft===0||','if(state.turnsLeft<0||'],
 ['full inventory shop allowed','state.inventory.length===3','state.inventory.length>3'],
 ['branch exact affordability rejected','branch.cost<=state.coins','branch.cost<state.coins'],
 ['illegal action accepted','action.legal&&action.cost','(action.legal||true)&&action.cost'],
 ['action exact affordability rejected','action.cost<=state.coins','action.cost<state.coins'],
 ['star budget equality loses branch bonus','branch.coinGain>=state.starPrice','branch.coinGain>state.starPrice'],
 ['affordable branch proximity bonus removed','?100:10','?0:10'],
 ['branch buddy gain removed','4*(state.buddy?0:branch.buddyGain)','0*(state.buddy?0:branch.buddyGain)'],
 ['action star utility removed','50*action.starGain','0*action.starGain'],
 ['branch risk penalty removed','-20*branch.risk','-0*branch.risk'],
 ['exact movement arrival bonus omitted','action.movement>=state.starDistance','action.movement>state.starDistance'],
 ['shop star reserve penalty removed','value-=30','value-=0'],
 ['exact star affordability rejected','state.coins<state.starPrice','state.coins<=state.starPrice']
];
