import assert from 'node:assert/strict';
import {writeFileSync} from 'node:fs';
import {performance} from 'node:perf_hooks';
import {validateTable,validatePosition,validatePlay,findBestPlay} from './dist/reference.js';
const colors=['red','blue','black','orange'];
const n=(id,color,value)=>({id,kind:'number',color,value});
const j=id=>({id,kind:'joker'});
const bound=(id,color,value)=>({...j(id),as:{color,value}});
const run=(color,start,end,prefix='n')=>({kind:'run',tiles:Array.from({length:end-start+1},(_,i)=>n(prefix+(start+i),color,start+i))});
const group=(value,cs=colors,prefix='g')=>({kind:'group',tiles:cs.map((c,i)=>n(prefix+i,c,value))});
const pos=(hand,table=[],initialMeldDone=true)=>({table,hand,initialMeldDone});
const counts={table:0,position:0,play:0,solver:0},cases=[];
function check(category,name,actual,expected){assert.equal(actual,expected,name);counts[category]++;cases.push(name);}
for(const [name,table] of [['empty',[]],['ascending',[run('red',1,13)]],['group3',[group(7,colors.slice(0,3))]],['group4',[group(13)]],['joker-run',[{kind:'run',tiles:[n('a','red',1),bound('j','red',2),n('b','red',3)]}]],['two-joker-group',[{kind:'group',tiles:[n('a','red',13),bound('j','blue',13),bound('k','black',13)]}]]])check('table',name,validateTable(table).ok,true);
for(const [name,table] of [['not-array',{}],['too-short',[{kind:'run',tiles:[n('a','red',1),n('b','red',2)]}]],['descending',[{kind:'run',tiles:[n('a','red',3),n('b','red',2),n('c','red',1)]}]],['run-gap',[{kind:'run',tiles:[n('a','red',1),n('b','red',2),n('c','red',4)]}]],['run-mixed-color',[{kind:'run',tiles:[n('a','red',1),n('b','red',2),n('c','blue',3)]}]],['wrap',[{kind:'run',tiles:[n('a','red',12),n('b','red',13),n('c','red',1)]}]],['group-mixed-value',[{kind:'group',tiles:[n('a','red',1),n('b','blue',1),n('c','black',2)]}]],['group-duplicate-color',[{kind:'group',tiles:[n('a','red',1),n('b','red',1),n('c','black',1)]}]],['unbound-joker',[{kind:'run',tiles:[n('a','red',1),n('b','red',2),j('j')]}]],['bad-joker-face',[{kind:'run',tiles:[n('a','red',1),n('b','red',2),bound('j','red',14)]}]],['duplicate-id',[{kind:'run',tiles:[n('a','red',1),n('a','red',2),n('c','red',3)]}]],['three-jokers',colors.slice(0,3).map((c,i)=>({kind:'run',tiles:[n('a'+i,c,1),n('b'+i,c,2),bound('j'+i,c,3)]}))],['third-physical-copy',[group(4,['red','blue','black'],'a'),group(4,['red','blue','orange'],'b'),group(4,['red','black','orange'],'c')]]])check('table',name,validateTable(table).ok,false);
check('position','empty-position',validatePosition(pos([])).ok,true);
check('position','whitespace-id',validatePosition(pos([j(' ')])).ok,true);
check('position','ignored-extra-keys',validatePosition({...pos([{...j('j'),as:{color:'nonsense',value:0},extra:5}]),extra:[]}).ok,true);
for(const [name,input] of [['empty-id',pos([j('')])],['third-copy',pos([n('a','red',1),n('b','red',1),n('c','red',1)])],['third-joker',pos([j('a'),j('b'),j('c')])],['fraction',pos([n('a','red',1.5)])],['nonfinite',pos([n('a','red',Infinity)])],['bad-color',pos([n('a','purple',1)])],['nonboolean',{...pos([]),initialMeldDone:1}],['shared-id',pos([n('n1','blue',7)],[run('red',1,3)])]])check('position',name,validatePosition(input).ok,false);
const old=[run('red',3,5)];
const opener=group(10,colors.slice(0,3),'o');
check('play','extension-opened',validatePlay(pos([n('a','red',2)],old),[run('red',2,5,'x')]).ok,false); // physical IDs differ
const extension=[{kind:'run',tiles:[n('a','red',2),...old[0].tiles]}];
check('play','valid-extension',validatePlay(pos([n('a','red',2)],old),extension).ok,true);
check('play','no-rack-tile',validatePlay(pos([],old),old).ok,false);
check('play','foreign-tile',validatePlay(pos([],old),[...old,opener]).ok,false);
check('play','missing-old',validatePlay(pos(opener.tiles,old),[opener]).ok,false);
check('play','opening-30',validatePlay(pos(opener.tiles,old,false),[opener,...old]).ok,true);
check('play','opening-cannot-extend',validatePlay(pos([...opener.tiles,n('a','red',2)],old,false),[opener,...extension]).ok,false);
const oldGroup=group(7,colors.slice(0,3),'x');
check('play','opening-group-order-irrelevant',validatePlay(pos(opener.tiles,[oldGroup],false),[opener,{...oldGroup,tiles:[...oldGroup.tiles].reverse()}]).ok,true);
const oldJ={kind:'group',tiles:[n('a','red',3),n('b','blue',3),bound('j','black',3)]};
const rebind={...oldJ,tiles:[oldJ.tiles[0],oldJ.tiles[1],bound('j','orange',3)]};
check('play','opening-binding-preserved',validatePlay(pos(opener.tiles,[oldJ],false),[rebind,opener]).ok,false);
check('play','opened-binding-profile',validatePlay(pos(opener.tiles,[oldJ]),[rebind,opener]).ok,true);
function solve(name,input,value,count){const before=JSON.stringify(input),start=performance.now(),r=findBestPlay(input),elapsed=performance.now()-start;assert.equal(r.ok,true,name);assert.equal(r.value,value,name+' value');assert.equal(r.played.length,count,name+' count');assert.equal(validateTable(r.table).ok,true,name+' output');if(r.action==='play'){const v=validatePlay(input,r.table);assert.equal(v.ok,true);assert.equal(v.value,r.value);assert.equal(v.rackPenaltyShed,r.rackPenaltyShed);}assert.equal(JSON.stringify(input),before,name+' immutability');counts.solver++;cases.push(name);return {name,elapsedMs:elapsed,value,count,stats:r.stats};}
const timings=[];
timings.push(solve('empty-pass',pos([]),0,0));
timings.push(solve('low-opening-pass',pos(run('red',1,3).tiles,[],false),0,0));
timings.push(solve('low-after-opening',pos(run('red',1,3).tiles),6,3));
timings.push(solve('high-opening',pos(run('red',10,12).tiles,[],false),33,3));
timings.push(solve('rack-joker-high-binding',pos([n('a','red',11),n('b','red',12),j('j')],[],false),36,3));
timings.push(solve('two-rack-jokers-high-group',pos([n('a','red',13),j('j'),j('k')],[],false),39,3));
timings.push(solve('old-extension',pos([n('a','red',2)],old),2,1));
timings.push(solve('opening-preserves-old',pos([...opener.tiles,n('a','red',2)],old,false),30,3));
timings.push(solve('opened-extends-and-melds',pos([...opener.tiles,n('a','red',2)],old),32,4));
const four=group(8,colors,'f');
timings.push(solve('extract-fourth-group-tile',pos([n('h7','blue',7),n('h9','blue',9)],[four]),16,2));
timings.push(solve('old-joker-new-set',pos([n('r3','red',3),n('b13','blue',13),n('k13','black',13)],[{kind:'run',tiles:[n('r1','red',1),n('r2','red',2),bound('j','red',3)]}]),29,3));
timings.push(solve('rack-and-table-joker-assignments',pos([j('new')],[{kind:'run',tiles:[n('r5','red',5),n('r6','red',6),bound('old','red',7)]}]),8,1));
timings.push(solve('large-16-complete-groups',pos([10,11,12,13].flatMap(v=>group(v,colors,'g'+v).tiles)),184,16));
const table40=colors.map(c=>run(c,1,10,c));
const hand20=[...colors.flatMap(c=>run(c,11,13,'h'+c).tiles),...['red','blue'].flatMap(c=>run(c,1,4,'dup'+c).tiles)];
timings.push(solve('large-40-table-20-hand',pos(hand20,table40),164,20));
const report={status:'passed',counts,total:Object.values(counts).reduce((a,b)=>a+b,0),cases,checks:timings.map(({elapsedMs,...check})=>check)};writeFileSync('SELFCHECK.json',JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify({status:report.status,counts,total:report.total,timings}));
