import {readFile,writeFile,mkdir,copyFile,readdir} from 'node:fs/promises';
import {createHash} from 'node:crypto';
const parse=async p=>JSON.parse(await readFile(p,'utf8'));
const summary=await parse('reports-run/summary.json');if(!summary.passed)throw new Error('No passing summary');for(const [file,digest] of Object.entries(summary.sourceSha256??{})){if(createHash('sha256').update(await readFile(file)).digest('hex')!==digest)throw new Error(`Evidence source changed: ${file}`);}
const seeds=await Promise.all([1,2,3].map(s=>parse(`reports-run/seed${s}.json`))),mutations=await parse('reports-run/mutations.json');
if(seeds.some(s=>!s.passed)||mutations.killed!==25||mutations.seededKills!==75)throw new Error('Incomplete suite');
await mkdir('reports',{recursive:true});for(const file of ['seed1.json','seed2.json','seed3.json','mutations.json','summary.json'])await copyFile(`reports-run/${file}`,`reports/${file}`);
const sounds=seeds.flatMap(s=>s.sounds),max=(f)=>Math.max(...sounds.map(f)),min=(f)=>Math.min(...sounds.map(f));
let doc=`# B17 verification\n\nFull local suite passed with Node 22.16.0, TypeScript 5.9.3 and FFmpeg 7.1.5.\nExact local command: \`npm exec --yes --package node@22.16.0 -c 'node --version && npm test'\`.\nCI installs the development compiler then runs exactly \`npm test\`.\n\nMachine-readable evidence: reports/seed1.json, seed2.json, seed3.json,\nmutations.json and summary.json. Each reports both implementations and exact\nexternal FFmpeg summaries. A failed suite exits nonzero and does not create a\npassing summary. The suite removes a previous summary at startup, and the\nsuccessful summary fingerprints all 15 code/configuration files; recording\nrejects a changed source fingerprint. SHA256 coverage includes every deliverable\nand checks the 30 MB per-file cap.\n\n## Per-seed suites\n\n| Test name | Cases per seed | Seeds | Passed | Exact command |\n| --- | ---: | --- | --- | --- |\n`;
for(const [key,count] of Object.entries(seeds[0].counts)){if(key.endsWith('Comparisons'))continue;doc+=`| ${key} | ${count} | 1, 2, 3 | ${seeds.every(s=>s.counts[key]===count)?'all':'see reports'} | \`npm test\` |\n`;}
doc+=`\nEach seed compares ${seeds[0].counts.rawSampleComparisons} raw samples and\n${seeds[0].counts.masteredSampleComparisons} independently mastered samples.\nThe quantized fade check compares ${seeds[0].counts.pcmFadeSampleComparisons} samples\nper seed (240 at each end × 40 sounds). The entire independently reconstructed\nPCM pipeline also matches every WAV byte, in addition to these edge checks.\n\n## Measured audio\n\n120 cases = 40 sounds × 3 seeds, each decoded from the final PCM16 WAV:\n\n| Quantity | Observed range / maximum | Required |\n| --- | --- | --- |\n| Duration | ${min(s=>s.seconds).toFixed(2)}–${max(s=>s.seconds).toFixed(2)} s | 0.05–3 s |\n| Integrated loudness | ${min(s=>s.production.lufs).toFixed(7)}–${max(s=>s.production.lufs).toFixed(7)} LUFS | −16 ±0.5 |\n| Highest 4× true peak | ${max(s=>s.production.truePeakDb).toFixed(7)} dBTP | ≤−1.5 |\n| Absolute DC offset | ${max(s=>Math.abs(s.production.dc)).toExponential(7)} | <0.001 |\n| Raw/reference sample error | ${max(s=>s.rawMaxError).toExponential(7)} | ≤1e−10 |\n| Master/reference sample error | ${max(s=>s.masterMaxError).toExponential(7)} | ≤1e−9 |\n\nBoth endpoint samples are exactly 0; the first and final adjacent sample jumps\nare below 0.001. All first/last 240 samples satisfy the independently reconstructed\n5 ms raised-cosine/DC-correction/mastering operation within PCM quantization.\nFFmpeg independently passes loudness/true-peak constraints on all 120 files.\nEvery WAV is byte-identical on regeneration. All 40 canonical WAVs and 40 PNGs\nplus 40 manifest hashes are checked under every seed.\n\n## EBU Tech 3341 calibration scope\n\nTen rebuilt **mono adaptations** of official Table 1 cases 1–5 and 15–19 are run\nunder each seed: 30/30 passes. Each official stereo integrated target is reduced\nby 10 log10(2)=3.01029995664 LU for one channel; true-peak targets are unchanged.\nBoth meters agree to 2e−8 on every numeric field; expected integrated tolerances\nare ±0.1 LU and true-peak tolerances are +0.2/−0.4 dB.\n\n| Rebuilt case | Seed 1 production result | Expected acceptance | Seeds 1/2/3 |\n| --- | --- | --- | --- |\n`;
for(const e of seeds[0].ebu){const field=e.expectedLufs?'lufs':'truePeakDb',bounds=e.expectedLufs??e.expectedTruePeak;doc+=`| ${e.id} | ${e.production[field].toFixed(9)} ${field==='lufs'?'LUFS':'dBTP'} | [${bounds.map(x=>x.toFixed(9)).join(', ')}] | pass/pass/pass |\n`;}
doc+=`\nThe meter resets filters on every call. The 120 deliverable comparisons use\ncomplete 400 ms blocks; incomplete trailing blocks are excluded. General inputs\nshorter than 400 ms are explicitly zero-padded by project convention and are not\npresent in delivered audio. Case 19 stays floating point to avoid PCM clipping.\nSources/recipes are in ORACLE.md and SOURCES.md.\n\n## 25 isolated source mutations\n\nEach copy starts from unmodified production source. Exactly one textual bug is\nplanted, that copy compiles successfully in strict TypeScript, and the unchanged\nbehavioral probe must fail an assertion for each seed. No mutation uses oracle\nedits, hardcoded simulated outcomes, or compilation failure as its kill.\n\n| # | Bug | Source | Seed 1 | Seed 2 | Seed 3 |\n| ---: | --- | --- | --- | --- | --- |\n`;
for(const m of mutations.mutations)doc+=`| ${m.index} | ${m.name} | ${m.file} | caught | caught | caught |\n`;
doc+=`\nFull source substitutions, successful compilation flags, exitcodes and real\nassertion output are in reports/mutations.json. Result: 25/25 source bugs, 75/75\nseeded probes. Temporary copies are deleted after the run.\n\n## Independence and CI\n\nThe reference author had no conversation fork and was forbidden to inspect\nproduction before sealing. The mathematical recipe and type contract were\nshared; implementation source was not. The exact initial reference is preserved\nas reference.snapshot.ts.txt (SHA256 625ea76450a7f7edf57a1637efae8bd037c0d5da5c889c6c0eba3d424fe22323).\nThe two narrow post-seal changes, their reasons and hashes are recorded in\nORACLE_AMENDMENTS.md. Source was never viewed by the reference author.\n\nThe first complete hosted run passed:\nhttps://github.com/luisitin/partybox-gpt-drops/actions/runs/37634170473\n(code revision 28dd7ba; full logs were inspected, all3 seeds and 25 mutations present).\nThe PR description links the final successful hosted run after publication.\nThe workflow has read-only contents permission, no secrets, a 30 minute timeout,\nand only actions/* pinned to major versions.\n\n## UNVERIFIED\n\n- Full EBU Mode certification, multichannel weighting, momentary/short-term\n  displays, loudness range, official programme-material cases 7/8, and cases 6–14/20–23\n  are outside this mono integrated/4× meter's verified scope. Passing the ten\n  rebuilt adaptations does not establish certification of the complete standard.\n- Subjective audition for taste and perceived game feel has not been performed.\n  The quantitative5 ms taper checks do not assert universal psychoacoustic\n  inaudibility for every listener or playback system.\n- Cross-engine byte identity beyond the pinned Node/V8 environment is not claimed.\n`;
await writeFile('VERIFY.md',doc);
const paths=[];async function walk(dir=''){for(const entry of await readdir(dir||'.',{withFileTypes:true})){const path=dir?`${dir}/${entry.name}`:entry.name;if(['node_modules','dist','reports-run','.mutations'].includes(entry.name))continue;if(entry.isDirectory())await walk(path);else if(entry.isFile()&&path!=='SHA256SUMS.txt')paths.push(path);}}await walk();paths.sort();let sums='';for(const path of paths)sums+=`${createHash('sha256').update(await readFile(path)).digest('hex')}  ${path}\n`;await writeFile('SHA256SUMS.txt',sums);
console.log(`Recorded successful evidence; checksummed ${paths.length} deliverable files.`);
