// Records a passing suite run: copies the run's evidence into reports/, writes the detailed measured tables to
// reports/polish-2026-10-08-tables.md, appends a short dated section to VERIFY.md (the first delivery's text above it
// stays as written) and refreshes SHA256SUMS.txt.
// Refuses to record unless the suite passed and every fingerprinted source is unchanged since that run.
import {readFile,writeFile,mkdir,copyFile,access} from 'node:fs/promises';
import {createHash} from 'node:crypto';
const hash=b=>createHash('sha256').update(b).digest('hex');
const parse=async p=>JSON.parse(await readFile(p,'utf8'));
const summary=await parse('reports-run/summary.json');if(!summary.passed)throw new Error('No passing summary');
for(const [file,digest] of Object.entries(summary.sourceSha256??{})){if(hash(await readFile(file))!==digest)throw new Error(`Evidence source changed: ${file}`);}
const seeds=await Promise.all([1,2,3].map(s=>parse(`reports-run/seed${s}.json`))),mutations=await parse('reports-run/mutations.json');
if(seeds.some(s=>!s.passed)||mutations.killed!==25||mutations.seededKills!==75)throw new Error('Incomplete suite');
// Keep the first delivery's evidence next to the new one.
const FILES=['seed1.json','seed2.json','seed3.json','mutations.json','summary.json'];
await mkdir('reports/v1-2026-10-07',{recursive:true});
for(const file of FILES){try{await access(`reports/v1-2026-10-07/${file}`);}catch{await copyFile(`reports/${file}`,`reports/v1-2026-10-07/${file}`);}}
await mkdir('reports',{recursive:true});
for(const file of FILES)await copyFile(`reports-run/${file}`,`reports/${file}`);
const sounds=seeds.flatMap(s=>s.sounds),legacy=seeds.flatMap(s=>s.legacy);
const max=(list,f)=>Math.max(...list.map(f)),min=(list,f)=>Math.min(...list.map(f));
const TABLES='reports/polish-2026-10-08-tables.md';
const MARK='## Polish pass 2026-10-08';
const ffmpegVersion=summary.ffmpeg.match(/version (\S+)/)?.[1]??'unknown';
const minus=text=>text.replace('-','−');

// Detailed tables: every measured number of the passing run, for anyone who wants to check the short section.
let tables=`# B17 polish pass 2026-10-08: measured tables\n\nGenerated by tools/record.mjs from reports-run/ (the passing run). Node ${summary.node}; FFmpeg ${ffmpegVersion}.\n\n`;
tables+=`## Per-seed suites\n\n| Test name | Cases per seed | Seeds | Passed | Exact command |\n| --- | ---: | --- | --- | --- |\n`;
for(const [key,count] of Object.entries(seeds[0].counts)){if(/SampleComparisons$/.test(key)||key==='pcmFadeSampleComparisons')continue;tables+=`| ${key} | ${count} | 1, 2, 3 | ${seeds.every(s=>s.counts[key]===count)?'all':'see reports'} | \`npm test\` |\n`;}
tables+=`\nSamples compared per seed: ${seeds[0].counts.legacyRawSampleComparisons} blind-oracle raw samples (v1 recipe), ${seeds[0].counts.stereoSampleComparisons} stereo samples (v2 engine against twin), ${seeds[0].counts.masteredSampleComparisons} mastered mono samples (v2). The quantized fade check compares ${seeds[0].counts.pcmFadeSampleComparisons} samples per seed (240 at each end × 40 sounds).\n\n`;
tables+=`## Shipped v2 audio (120 cases = 40 sounds × 3 seeds, decoded from the final PCM16 WAV)\n\n| Quantity | Observed range / maximum | Required |\n| --- | --- | --- |\n`;
tables+=`| Duration | ${min(sounds,s=>s.seconds).toFixed(2)}–${max(sounds,s=>s.seconds).toFixed(2)} s | 0.05–3 s |\n`;
tables+=`| Integrated loudness | ${min(sounds,s=>s.production.lufs).toFixed(7)}–${max(sounds,s=>s.production.lufs).toFixed(7)} LUFS | −16 ±0.5 |\n`;
tables+=`| Highest 4× true peak | ${max(sounds,s=>s.production.truePeakDb).toFixed(7)} dBTP | ≤−1.5 |\n`;
tables+=`| Largest sample peak | ${(20*Math.log10(max(sounds,s=>s.production.samplePeak))).toFixed(7)} dBFS | ≤−1.5 |\n`;
tables+=`| Absolute DC offset | ${max(sounds,s=>Math.abs(s.production.dc)).toExponential(7)} | <0.001 |\n`;
tables+=`| Stereo engine vs twin | ${max(sounds,s=>s.stereoMaxError).toExponential(7)} | ≤1e−9 |\n`;
tables+=`| Mastered vs independent master | ${max(sounds,s=>s.masterMaxError).toExponential(7)} | ≤1e−9 |\n`;
tables+=`| External FFmpeg loudness / true peak (ebur128, peak=true) | all 120 within 0.11 LU and 0.4 dB of the production meter | same limits |\n\n`;
tables+=`Endpoint samples are exactly 0 and the first and last adjacent jumps are below 0.001. Every WAV is byte-identical on regeneration. All 40 canonical WAVs, 40 spectrogram PNGs (256×128) and the manifest hashes are checked under every seed. \`renderCue\` returns exactly the delivered seed-1 mono master for all 40 sounds.\n\n`;
tables+=`## Shipped sounds (seed 1)\n\n| Sound | Group | Seconds | LUFS | dBTP | Sample peak dBFS | DC | SHA-256 (first 12) |\n| --- | --- | ---: | ---: | ---: | ---: | ---: | --- |\n`;
for(const s of seeds[0].sounds)tables+=`| ${s.id} | ${s.group} | ${s.seconds.toFixed(3)} | ${s.production.lufs.toFixed(2)} | ${s.production.truePeakDb.toFixed(2)} | ${(20*Math.log10(s.production.samplePeak)).toFixed(2)} | ${s.production.dc.toExponential(1)} | \`${s.sha256.slice(0,12)}\` |\n`;
tables+=`\n## First delivery's recipe (legacy.ts) through the shared stack\n\nBlind-oracle comparisons against reference.ts, the sealed implementation written without seeing production:\n\n| Check | Seeds 1/2/3 maximum | Required |\n| --- | --- | --- |\n`;
tables+=`| Raw sample error | ${seeds.map(s=>max(s.legacy,r=>r.rawMaxError).toExponential(3)).join(' / ')} | ≤1e−10 |\n| Mastered sample error | ${seeds.map(s=>max(s.legacy,r=>r.masterMaxError).toExponential(3)).join(' / ')} | ≤1e−9 |\n| Full PCM bytes equal the independent pipeline | 40/40 each seed | byte-identical |\n\n`;
tables+=`## EBU Tech 3341 calibration scope\n\nTen rebuilt **mono adaptations** of official Table 1 cases 1–5 and 15–19 are run under each seed: 30/30 passes. Each official stereo integrated target is reduced by 10 log10(2)=3.01029995664 LU for one channel; true-peak targets are unchanged. The expected acceptance ranges are unchanged from the first delivery.\n\n| Rebuilt case | Seed 1 production result | Expected acceptance |\n| --- | --- | --- |\n`;
for(const e of seeds[0].ebu){const field=e.expectedLufs?'lufs':'truePeakDb',bounds=e.expectedLufs??e.expectedTruePeak;tables+=`| ${e.id} | ${e.production[field].toFixed(9)} ${field==='lufs'?'LUFS':'dBTP'} | [${bounds.map(x=>x.toFixed(9)).join(', ')}] |\n`;}
tables+=`\n## 25 isolated source mutations (v2)\n\nEach copy starts from unmodified production source and plants exactly one textual bug. Six bugs moved from sfx.ts (first delivery) to dsp.ts (v2 engine), which the twin cross-check now guards; the meter and WAV bugs are unchanged. Each copy compiles under strict TypeScript and the behavioural probe must fail an AssertionError under each seed.\n\n| # | Bug | Source | Seed 1 | Seed 2 | Seed 3 |\n| ---: | --- | --- | --- | --- | --- |\n`;
for(const m of mutations.mutations)tables+=`| ${m.index} | ${m.name} | ${m.file} | ${m.seeds[0].killed?'caught':'MISSED'} | ${m.seeds[1].killed?'caught':'MISSED'} | ${m.seeds[2].killed?'caught':'MISSED'} |\n`;
tables+=`\nResult: ${mutations.killed}/25 source bugs, ${mutations.seededKills}/75 seeded probes. The first delivery's 25 mutations (sfx.ts v1 anchors) are in reports/v1-2026-10-07/mutations.json.\n\n`;
tables+=`## Source fingerprint\n\nThe passing summary fingerprints ${Object.keys(summary.sourceSha256).length} code and configuration files (meter, wav, sfx, spectrogram, dsp, recipes, cues, legacy, twin, reference, tests, tools, tsconfig, package files). record.mjs refuses to write if any of them changed after the run.\n`;
await writeFile(TABLES,tables);

// The VERIFY.md section stays short: the result, the measured ranges, and what the checks do not prove.
const previous=await readFile('VERIFY.md','utf8');
const head=previous.includes(MARK)?previous.slice(0,previous.indexOf(MARK)).trimEnd():previous.trimEnd();
const lufsMin=min(sounds,s=>s.production.lufs).toFixed(3),lufsMax=max(sounds,s=>s.production.lufs).toFixed(3);
let doc=`\n\n${MARK} (v2 engine; generated by tools/record.mjs)\n\n`;
doc+=`Command: \`npm test\` (TypeScript 5.9.3, then tests/run.mjs). Node ${summary.node} locally (CI pins 22.16.0); FFmpeg ${ffmpegVersion}. Result: passed.\n\n`;
doc+=`- Seeds 1, 2 and 3: the first delivery's recipe (legacy.ts) through the shared master, encoder and meter, checked against the blind oracle (reference.ts). The 40 shipped v2 sounds are checked against twin.ts, the master, the WAV bytes and FFmpeg ebur128.\n`;
const lufsSpread=max(sounds,s=>s.production.lufs)-min(sounds,s=>s.production.lufs);
const loudness=lufsSpread<0.0005?`${minus(lufsMin)} LUFS on every case`:`${minus(lufsMin)} to ${minus(lufsMax)} LUFS`;
doc+=`- Shipped audio (120 decoded WAV cases): duration ${min(sounds,s=>s.seconds).toFixed(2)}–${max(sounds,s=>s.seconds).toFixed(2)} s; integrated loudness ${loudness} (target −16 ±0.5); 4× true peak from ${minus(min(sounds,s=>s.production.truePeakDb).toFixed(2))} to ${minus(max(sounds,s=>s.production.truePeakDb).toFixed(2))} dBTP (limit −1.5); largest |DC| ${max(sounds,s=>Math.abs(s.production.dc)).toExponential(1)}.\n`;
doc+=`- The engine agrees with its twin to ${max(sounds,s=>s.stereoMaxError).toExponential(1)} and the mastered output with the independent master to ${max(sounds,s=>s.masterMaxError).toExponential(1)} (limit 1e−9).\n`;
doc+=`- FFmpeg ebur128 agrees with the production meter within 0.11 LU and 0.4 dB on all 120 cases.\n`;
doc+=`- Rebuilt EBU Tech 3341 mono cases 1–5 and 15–19: 30/30 pass (10 per seed). The first delivery's calibration scope above still applies.\n`;
doc+=`- 25 planted source bugs (meter.ts, wav.ts, dsp.ts), each killed under seeds 1, 2 and 3: 75/75.\n\n`;
doc+=`Detailed tables (per-sound measurements and hashes, EBU rows, mutation matrix): \`reports/polish-2026-10-08-tables.md\`. Raw evidence: \`reports/seed1.json\` to \`seed3.json\`, \`reports/mutations.json\`, \`reports/summary.json\`. The first delivery's evidence is in \`reports/v1-2026-10-07/\`.\n\n`;
doc+=`### UNVERIFIED\n\n- No listening test. Everything here is measured, not auditioned.\n- \`twin.ts\` is not blind: it is a second implementation of \`dsp.ts\` by the same author. A misreading shared by both would pass.\n- Spectral balance is not a suite check. The spectrograms are for inspection (\`gallery.html\`).\n- Full EBU Mode certification, momentary and short-term loudness, loudness range and programme cases 6–14 and 20–23 are out of scope.\n- Cross-engine byte identity is not claimed: the engine uses \`Math.sin\`, \`Math.exp\` and \`Math.pow\`, which may differ in the last bit between engines.\n- The \`trimDb\` values in \`cues.ts\` are proposals, not measured against PartyBox's own voices.\n`;
await writeFile('VERIFY.md',head+doc);
await import('./checksums.mjs');
console.log(`Recorded successful v2 evidence; VERIFY.md, ${TABLES} and SHA256SUMS.txt updated.`);
