// Forty manually specified expectations. None is computed by either solver.
const C = { r: 'red', b: 'blue', k: 'black', o: 'orange' };
export const N = (c, value, copy = 'a') => ({ id: `${c}${value}${copy}`, kind: 'number', color: C[c], value });
export const J = (id, c, value) => ({ id, kind: 'joker', as: { color: C[c], value } });
export const HJ = (id = 'J0') => ({ id, kind: 'joker' });
export const R = (...tiles) => ({ kind: 'run', tiles });
export const G = (...tiles) => ({ kind: 'group', tiles });
export const P = (table, hand, initialMeldDone = true) => ({ table, hand, initialMeldDone });
const T = (id, name, input, expected) => ({ id, name, type: 'table', input, expected });
const V = (id, name, before, after, expected) => ({ id, name, type: 'play', before, after, expected });
export const jokerCases = [
  T('J01', 'Leading joker can represent 1', [R(J('J0','r',1),N('r',2),N('r',3))], true),
  T('J02', 'Trailing joker can represent 13', [R(N('k',11),N('k',12),J('J0','k',13))], true),
  T('J03', 'Interior gap filled by joker', [R(N('b',5),J('J0','b',6),N('b',7))], true),
  T('J04', 'Two consecutive jokers in a run', [R(N('r',8),J('J0','r',9),J('J1','r',10))], true),
  T('J05', 'Two endpoint jokers with one natural tile', [R(J('J0','o',1),N('o',2),J('J1','o',3))], true),
  T('J06', 'Two jokers in a three-tile group', [G(N('r',7),J('J0','b',7),J('J1','k',7))], true),
  T('J07', 'Two jokers in a four-tile group', [G(N('r',7),N('b',7),J('J0','k',7),J('J1','o',7))], true),
  T('J08', 'First absent color in a three-tile group', [G(N('r',3),N('b',3),J('J0','k',3))], true),
  T('J09', 'Other absent color in a three-tile group', [G(N('r',3),N('b',3),J('J0','o',3))], true),
  T('J10', 'Two joker bindings cannot duplicate a group color', [G(N('r',7),J('J0','b',7),J('J1','b',7))], false),
  T('J11', 'Joker group number must agree', [G(N('r',7),N('b',7),J('J0','k',8))], false),
  T('J12', 'Joker cannot duplicate a natural group color', [G(N('r',7),N('b',7),J('J0','r',7))], false),
  T('J13', 'Joker run color must agree', [R(N('r',5),J('J0','b',6),N('r',7))], false),
  T('J14', 'An incorrectly bound joker does not bridge a gap', [R(N('r',5),J('J0','r',7),N('r',8))], false),
  T('J15', 'No 13-to-1 wrap through a joker', [R(N('r',12),N('r',13),J('J0','r',1))], false),
  T('J16', 'A joker cannot represent zero', [R(J('J0','r',0),N('r',1),N('r',2))], false),
  T('J17', 'A joker cannot represent fourteen', [R(N('r',12),N('r',13),J('J0','r',14))], false),
  T('J18', 'Unbound table joker is rejected', [R(N('r',1),HJ(),N('r',3))], false),
  T('J19', 'The whole table may not contain three physical jokers',
    [R(N('r',1),J('J0','r',2),J('J1','r',3)),R(N('b',1),J('J2','b',2),N('b',3))], false),
  T('J20', 'One physical joker cannot occur in two melds',
    [R(N('r',1),J('J0','r',2),N('r',3)),R(N('b',1),J('J0','b',2),N('b',3))], false),
  T('J21', 'Two distinct jokers may occur in separate melds',
    [R(N('r',1),J('J0','r',2),N('r',3)),R(N('b',4),J('J1','b',5),N('b',6))], true),
  T('J22', 'A represented face does not count as a third physical numbered copy',
    [R(N('r',3),N('r',4),N('r',5)),R(N('r',3,'b'),N('r',4,'b'),N('r',5,'b')),R(J('J0','r',5),N('r',6),N('r',7))], true),
  T('J23', 'Three physical numbered copies remain illegal with a joker present',
    [R(N('r',3),N('r',4),N('r',5)),R(N('r',3,'b'),N('r',4,'b'),N('r',5,'b')),R(N('r',5,'c'),N('r',6),J('J0','r',7))], false),
  T('J24', 'Two jokers alone are not a meld', [R(J('J0','r',1),J('J1','r',2))], false),
  T('J25', 'Fractional joker bindings are invalid', [R(N('r',1),J('J0','r',2.5),N('r',3))], false),
  V('J26', 'Exactly 30 opens; joker contributes 11, not 30',
    P([], [N('r',9),N('r',10),HJ()], false), [R(N('r',9),N('r',10),J('J0','r',11))], true),
  V('J27', 'A 27-point joker opening fails',
    P([], [N('r',8),N('r',9),HJ()], false), [R(N('r',8),N('r',9),J('J0','r',10))], false),
  V('J28', 'Exactly 29 fails even across two sets',
    P([], [N('b',2),N('b',3),N('b',4),N('b',5),N('r',5),N('k',5),HJ()], false),
    [R(N('b',2),N('b',3),N('b',4),N('b',5)),G(N('r',5),N('k',5),J('J0','o',5))], false),
  V('J29', 'Opening turn cannot also extend the table',
    P([R(N('r',1),N('r',2),N('r',3))], [N('r',4),N('r',10),N('r',11),HJ()], false),
    [R(N('r',1),N('r',2),N('r',3),N('r',4)),R(N('r',10),N('r',11),J('J0','r',12))], false),
  V('J30', 'Opening cannot retrieve an old table joker',
    P([G(N('r',10),N('b',10),J('J0','k',10))], [N('k',10),N('r',11),N('r',12)], false),
    [G(N('r',10),N('b',10),N('k',10)),R(N('r',11),N('r',12),J('J0','r',13))], false),
  V('J31', 'Opening preserves the explicit bindings of old jokers',
    P([G(N('r',10),N('b',10),J('J0','k',10))], [N('k',9),N('k',10),HJ('J1')], false),
    [G(N('r',10),N('b',10),J('J0','o',10)),R(N('k',9),N('k',10),J('J1','k',11))], false),
  V('J32', 'One rack tile anywhere on turn suffices for joker retrieval',
    P([G(N('r',3),N('b',3),J('J0','k',3)),R(N('k',8),N('k',9),N('k',10))], [N('k',3)]),
    [G(N('r',3),N('b',3),N('k',3)),R(N('k',8),N('k',9),N('k',10),J('J0','k',11))], true),
  V('J33', 'The other absent group color also retrieves the joker',
    P([G(N('r',3),N('b',3),J('J0','k',3)),R(N('k',8),N('k',9),N('k',10))], [N('o',3)]),
    [G(N('r',3),N('b',3),N('o',3)),R(N('k',8),N('k',9),N('k',10),J('J0','k',11))], true),
  V('J34', 'A shifted run can free a joker without an exact-number replacement',
    P([R(N('b',6),N('b',7),J('J0','b',8))], [N('b',5),N('r',10),N('r',11)]),
    [R(N('b',5),N('b',6),N('b',7)),R(N('r',10),N('r',11),J('J0','r',12))], true),
  V('J35', 'Splitting the old run can free its interior joker',
    P([R(N('r',2),N('r',3),J('J0','r',4),N('r',5),N('r',6))], [N('r',1),N('r',7),N('k',10),N('k',11)]),
    [R(N('r',1),N('r',2),N('r',3)),R(N('r',5),N('r',6),N('r',7)),R(N('k',10),N('k',11),J('J0','k',12))], true),
  V('J36', 'Dissolving a joker run into other groups is allowed',
    P([R(N('k',1),N('k',2),J('J0','k',3)),G(N('r',1),N('b',1),N('o',1)),G(N('r',2),N('b',2),N('o',2))], [N('r',10),N('r',11)]),
    [G(N('k',1),N('r',1),N('b',1),N('o',1)),G(N('k',2),N('r',2),N('b',2),N('o',2)),R(N('r',10),N('r',11),J('J0','r',12))], true),
  V('J37', 'A retrieved joker cannot return to the rack',
    P([G(N('r',3),N('b',3),J('J0','k',3))], [N('k',3)]), [G(N('r',3),N('b',3),N('k',3))], false),
  V('J38', 'A foreign joker cannot replace an owned one',
    P([R(N('r',1),N('r',2),N('r',3))], [N('b',5),N('b',6),HJ()]),
    [R(N('r',1),N('r',2),N('r',3)),R(N('b',5),N('b',6),J('J1','b',7))], false),
  V('J39', 'Table-only rearrangement is not a play',
    P([R(N('r',1),N('r',2),J('J0','r',3)),G(N('r',3),N('b',3),N('k',3))], []),
    [R(N('r',1),N('r',2),N('r',3)),G(N('b',3),N('k',3),J('J0','o',3))], false),
  V('J40', 'Both table jokers may be rearranged in one legal turn',
    P([R(N('r',1),N('r',2),J('J0','r',3)),R(N('b',4),N('b',5),J('J1','b',6))], [N('r',3),N('b',6)]),
    [R(N('r',1),N('r',2),N('r',3)),R(N('b',4),N('b',5),N('b',6),J('J0','b',7),J('J1','b',8))], true),
];
