import{readFile,writeFile,mkdir}from'node:fs/promises';import{candidateRgb,pair,MODES,simulate,DARK,LIGHT}from'../dist/color.js';import{encodePng16}from'../dist/png.js';
const WIDTH=640,HEIGHT=384,CELL_W=160,CELL_H=128;
const digits=['111101101101111','010110010010111','111001111100111','111001111001111','101101111001001','111100111001111','111100111101111','111001001001001','111101111101111','111101111001111'];
export function swatchPixels(colors,mode){const pixels=new Uint16Array(WIDTH*HEIGHT*3);for(let y=0;y<HEIGHT;y++)for(let x=0;x<WIDTH;x++){const i=Math.floor(y/CELL_H)*4+Math.floor(x/CELL_W),localX=x%CELL_W,localY=y%CELL_H,c=colors[i],fill=localX>=16&&localX<144&&localY>=20&&localY<108;let rgb=simulate(fill?c.rgb:(localX<80?DARK:LIGHT),mode);const label=String(i+1).padStart(2,'0');for(let digit=0;digit<2;digit++){const dx=Math.floor((localX-(digit===0?54:82))/8),dy=Math.floor((localY-44)/8);if(dx>=0&&dx<3&&dy>=0&&dy<5&&digits[Number(label[digit])][dy*3+dx]==='1')rgb=simulate(c.text==='#000000'?[0,0,0]:[1,1,1],mode);}const offset=(y*WIDTH+x)*3;for(let k=0;k<3;k++)pixels[offset+k]=Math.round(rgb[k]*65535);}return pixels;}
export async function generate(){const input=JSON.parse(await readFile('palette.json','utf8')),colors=input.colors.map(c=>({...candidateRgb(c.rgb),name:c.name}));await mkdir('swatches',{recursive:true});await mkdir('tables',{recursive:true});const rows=[];for(let i=0;i<12;i++)for(let j=i+1;j<12;j++){const distances=pair(colors[i],colors[j]);for(const mode of MODES)rows.push({first:i+1,second:j+1,firstName:colors[i].name,secondName:colors[j].name,mode,distance:distances[mode],required:mode==='normal'&&j<8?20:12,passed:distances[mode]>=(mode==='normal'&&j<8?20:12)});}const failures=rows.filter(row=>!row.passed),contrasts=colors.map((c,i)=>({number:i+1,name:c.name,rgb:c.rgb,css:c.css,hexApproximation:c.hex,text:c.text,textContrast:c.textContrast,darkContrast:c.darkContrast,lightContrast:c.lightContrast,passed:c.textContrast>=4.5&&c.darkContrast>=3&&c.lightContrast>=3}));
await writeFile('tables/pairwise.json',JSON.stringify(rows,null,2)+'\n');await writeFile('tables/contrast.json',JSON.stringify(contrasts,null,2)+'\n');await writeFile('tables/pairwise.csv','first,second,firstName,secondName,mode,distance,required,passed\n'+rows.map(r=>[r.first,r.second,r.firstName,r.secondName,r.mode,r.distance,r.required,r.passed].join(',')).join('\n')+'\n');
let md='# Full pairwise CIEDE2000 tables\n\nValues below are rounded for display; acceptance uses full binary64 values in pairwise.json. First eight: normal ≥20. Every pair: all four views ≥12.\n\n';for(const mode of MODES){md+=`## ${mode}\n\n| # | ${colors.map((c,i)=>i+1).join(' | ')} |\n| --- | ${colors.map(()=> '---').join(' | ')} |\n`;for(let i=0;i<12;i++)md+=`| ${i+1} | ${colors.map((_,j)=>i===j?'0':pair(colors[i],colors[j])[mode].toFixed(6)).join(' | ')} |\n`;md+='\n';await writeFile(`swatches/${mode}.png`,encodePng16(WIDTH,HEIGHT,swatchPixels(colors,mode)));}await writeFile('tables/PAIRWISE.md',md);
const extrema=Object.fromEntries(MODES.map(mode=>[mode,Math.min(...rows.filter(r=>r.mode===mode).map(r=>r.distance))]));const acceptance={passed:failures.length===0&&contrasts.every(c=>c.passed),pairChecks:rows.length,contrastChecks:36,failures,minimumAll12:extrema,minimumFirst8Normal:Math.min(...rows.filter(r=>r.mode==='normal'&&r.second<=8).map(r=>r.distance)),optionalMinimumFirst8AllViews:Math.min(...rows.filter(r=>r.second<=8).map(r=>r.distance)),png:{width:WIDTH,height:HEIGHT,bitDepth:16,quantization:'nearest integer channel / 65535; actual palette acceptance measures unrounded RGB vectors'}};await writeFile('tables/acceptance.json',JSON.stringify(acceptance,null,2)+'\n');
const html=`<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>B16 player colors</title><style>body{font:16px system-ui;max-width:1000px;margin:24px auto;padding:0 16px}article{display:grid;grid-template-columns:1fr 1fr;gap:12px;margin-bottom:20px}.background{padding:16px}.dark{background:#121218}.light{background:#F7F5F0}.fill{padding:18px;border-radius:8px;text-align:center}code{overflow-wrap:anywhere}img{width:100%;image-rendering:auto}</style><h1>B16 player colors</h1><p>Exact CSS sRGB colors below. Hex values are eight-bit approximations. ${acceptance.passed?'All specified numerical palette constraints pass.':'Some specified numerical distances remain below threshold; see the full acceptance report.'}</p>${colors.map((c,i)=>`<h2>${i+1}. ${c.name}</h2><p><code>${c.css}</code>; text <code>${c.text}</code>; approximate hex <code>${c.hex}</code></p><article>${['dark','light'].map(bg=>`<div class="background ${bg}"><div class="fill" style="background:${c.css};color:${c.text}">${c.name}</div></div>`).join('')}</article>`).join('')}<h2>Machado severity 1.0</h2>${MODES.map(mode=>`<h3>${mode}</h3><img src="swatches/${mode}.png" alt="${mode} simulation of the numbered twelve colors">`).join('')}<p><a href="tables/PAIRWISE.md">Full pair tables</a> · <a href="tables/acceptance.json">Acceptance report</a></p></html>`;await writeFile('gallery.html',html+'\n');console.log(JSON.stringify(acceptance,null,2));return{colors,rows,contrasts,acceptance};}
if(process.argv[1]?.endsWith('/generate.mjs'))await generate();
